spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:v2ray}?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-wait: 30000
    validation-query: select 1
    validation-interval: 10000
    validation-query-timeout: 5000
    max-active: 20
    max-idle: 20
    maximum-pool-size: 20
    remove-abandoned: true
    test-while-idle: true
    min-idle: 0
    num-tests-per-eviction-run: 3
mybatis:
  mapper-locations: classpath*:com/github/cnproxy/**/*Mapper.xml
pagehelper:
  row-bounds-with-count: true
  auto-dialect: true
  reasonable: false
logging:
  level:
    java.sql: DEBUG
    com.github.cnproxy: DEBUG